### ISSUE TITLE
Make the certificates configurable

### ISSUE THREAD

**Issue by tomekowal** [pdincau/mockapn#1]
Hey, I would like to use this library as a dependency for testing https://github.com/inaka/apns4erl/ The first think, I probably need to do, is to make some things configurable.

If you have any thoughts on doing it, I can follow your instructions. Otherwise, I will simply create a pull request moving certfile, keyfile and password to config file.

**Comment by pdincau** [comment]
Hi, sure the pull request is ok. I should probably specify a way to contribute to the project. Are you planning to use it? I don't know if it still works...can you let me know so that I will be able to work again on this project?

**Comment by tomekowal** [comment]
Thanks for the merge.
I think, I will use it. The project works for me and I was able to run tests from https://github.com/inaka/apns4erl/ on it. `apns4erl` used sandbox environment for testing. This has one big advantage, that if they change the API, tests will be broken.
But using `mockapn` is great, because I don't need real Apple certificate. I can just generate fake ones for tests and include it in the repository. I can also close the connection to simulate problems with network very easily.

**Comment by pdincau** [comment]
Great! Just let me know if you need anything
